//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Sp.Samples.BuildIntegration
{
	partial class SpAgent
	{
		// NOTE: This value needs to reflect the specific permutation package you are using to protect your app
		const string PermutationShortId = "c638d"; 
	 }
}
